
authorName: xiaonasu
experimentName: ImmuBLAST

trialConcurrency: 1
maxExecDuration: 156h
maxTrialNum: 2

trainingServicePlatform: local
searchSpacePath: search_space.json
useAnnotation: false
logDir: /aaa/louisyuzhao/guy2/xiaonasu/ImmuneBLAST_finalVersion/result/pretrain/test

multiThread: false
tuner:
    builtinTunerName: TPE
    classArgs:
        optimize_mode: maximize
    gpuIndices: "0,1,2,3,4,5,6,7"
trial:
    command: bash train.sh
    codeDir: ./
    gpuNum: 8

localConfig:
    maxTrialNumPerGpu: 1
    useActiveGpu: true